[package]
name = "postgrustql"
version = "0.1.0"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
async-graphql = "2.10.0"
async-graphql-parser = "2.10.1"
convert_case = "0.4.0"
futures = "0.3.17"
graphql-parser = "0.3.0"
petgraph = "0.6.0"
postgres = "0.19.1"
serde_json = "1.0.68"
tokio = { version = "0.2", features = ["macros", "tcp", "dns", "io-util"] }

