[package]
name = "postgrustql"
version = "0.1.0"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
Inflector = "0.11.4"
async-graphql-parser = "2.10.1"
async-graphql-value = "2.10.2"
convert_case = "0.4.0"
petgraph = "0.6.0"
postgres = "0.19.2"
