[package]
name = "postgrustql"
version = "0.1.0"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "2.0"
async-graphql-actix-web = "2.0"
Inflector = "0.11.4"
convert_case = "0.4.0"
graphql-parser = "0.3.0"
postgres = "0.19.1"
actix-rt = "2.2.0"
tokio = { version = "0.2", features = ["macros", "tcp", "dns", "io-util"] }
serde_json = "1.0.66"
