FROM rust as builder
WORKDIR app
COPY . .

# This works with the dummy project generated by `cargo new app --bin`
RUN cargo build --release 
FROM rust as runtime
WORKDIR app
COPY --from=builder /app/target/release/poggers /usr/local/bin
ENTRYPOINT ["./usr/local/bin/app"]
